# Unit Asset Trading (Model: Random Forest)
---

## 1. Data Model
### 1.1 Design $X_t$ (source: yfinance)
| **Parameter** | **Value**                      |
|---------------|--------------------------------|
| Asset         | IBIT (Blackrock Bitcoin ETF)   |
| Interval      | 5 mins                         |
| Period        | 1 month                        |

In [1]:
# Define the ticker symbol and interval
ticker = 'IBIT'
interval = '5m'
period = '1mo'

In [2]:
import yfinance as yf
import pandas as pd
import sys
import os

# Add the root directory to the Python path
sys.path.append(os.path.abspath('../..'))

IBIT = yf.download(ticker, period=period, interval=interval)\
        .droplevel(1, axis=1)\
        .reset_index()

[*********************100%***********************]  1 of 1 completed

In [3]:
from atlas.data import Data

at = Data(IBIT)
at.df

Price,Datetime,Close,High,Low,Open,Volume,date,log_return,volatility,delta,rsi,low_min,high_max,stochastic_oscillator,williams_r,macd_line,signal_line,proc,obv
0,2024-12-17 14:30:00+00:00,61.230000,61.419998,61.172298,61.334999,4226658,2024-12-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,0.0
1,2024-12-17 14:35:00+00:00,61.162201,61.299999,60.964401,61.230000,1841241,2024-12-17,-0.001108,0.001108,-0.067799,NaN,NaN,NaN,NaN,NaN,-0.005408,-0.001082,NaN,-1841241.0
2,2024-12-17 14:40:00+00:00,61.419899,61.490002,60.980301,61.169899,1564515,2024-12-17,0.004205,0.004205,0.257698,NaN,NaN,NaN,NaN,NaN,0.010973,0.001329,NaN,-276726.0
3,2024-12-17 14:45:00+00:00,61.540001,61.549999,61.389999,61.410198,1544052,2024-12-17,0.001954,0.001954,0.120102,NaN,NaN,NaN,NaN,NaN,0.033263,0.007716,NaN,1267326.0
4,2024-12-17 14:50:00+00:00,61.584999,61.649101,61.483299,61.535000,2141986,2024-12-17,0.000731,0.000731,0.044998,NaN,NaN,NaN,NaN,NaN,0.053937,0.016960,NaN,3409312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1519,2025-01-16 20:35:00+00:00,57.185001,57.290001,57.169998,57.220001,371625,2025-01-16,-0.000699,0.000699,-0.039997,74.365935,56.794498,57.268299,82.419246,-17.580754,0.139991,0.124840,0.002718,-53703616.0
1520,2025-01-16 20:40:00+00:00,57.189999,57.250000,57.169998,57.185001,286096,2025-01-16,0.000087,0.000087,0.004997,73.765186,56.904999,57.268299,78.447452,-21.552548,0.136704,0.127213,0.000787,-53417520.0
1521,2025-01-16 20:45:00+00:00,57.169998,57.259998,57.080002,57.200001,471841,2025-01-16,-0.000350,0.000350,-0.020000,67.866733,56.910000,57.268299,72.564572,-27.435428,0.130975,0.127965,0.001051,-53889361.0
1522,2025-01-16 20:50:00+00:00,57.230000,57.259998,57.150002,57.160000,675787,2025-01-16,0.001049,0.001049,0.060001,70.085335,57.029999,57.268299,83.928028,-16.071972,0.129781,0.128329,0.001598,-53213574.0
1523,2025-01-16 20:55:00+00:00,57.080002,57.259998,57.029999,57.230000,1863013,2025-01-16,-0.002624,0.002624,-0.149998,49.347877,57.029999,57.268299,20.983208,-79.016792,0.115401,0.125743,-0.001137,-55076587.0